.\" Manpage for lapp.
.\" Github repository: https://github.com/Zakaria742/lapp.git

.TH miw 1 "29 August 2025" "1.0" "miw man page"
.SH NAME
miw \- pixelization CLI app
.SH SYNOPSIS
miw [image]
.SH DESCRIPTION
miw(making it worse) is a pixelization-isque CLI app that takes an image as an input, outputing two files: a .txt and .png
.SH AUTHOR
Written by Zakaria742. (github : https://github.com/Zakaria742)
